#!/usr/local/bin/python3
# 
# Extracts alpha contents of the two provided data files. This is the lines
# that are NOT shared/common between the two files (meaning, the unique
# lines).

import sys
import argparse

parser = argparse.ArgumentParser(description="Extracts alpha contents of the two provided data files. This is the lines that are NOT shared/common between the two files (meaning, the unique lines).")
parser.add_argument("-i", "--input", required=True, nargs=2, type=argparse.FileType('r'), action="store", dest="inputFiles", metavar=('file1', 'file2'), help="exactly two files to extract alpha contents from")
parser.add_argument("-o", "--output", required=False, nargs='?', type=argparse.FileType('w'), default=sys.stdout, metavar="file", help="desired output (default: standard out)")
args = parser.parse_args()

alphaContents = []
file2Contents = set()
for line in args.inputFiles[1]:
	file2Contents.add(line.strip())
for line in args.inputFiles[0]:
	line = line.strip()
	if line in file2Contents:
		file2Contents.remove(line)
	else:
		alphaContents.append(line)
for line in file2Contents:
	alphaContents.append(line)

if alphaContents:
	for line in alphaContents:
		args.output.write(line)
		args.output.write("\n")
else:
	print("No unique data between the two files, no alpha file will be created")

args.output.close()
args.inputFiles[0].close()
args.inputFiles[1].close()